package org.gt.carjs;

import java.util.Arrays;
import java.util.HashSet;
import java.util.List;
import java.util.Set;

public class Props {
	public static List<String> windowProps;
	static {
		String[] windowPropsRaw = { "top", "window", "location", "chromium",
				"chrome", "external", "document", "names",
				"SVGPathSegLinetoVerticalRel", "SVGFESpotLightElement",
				"HTMLButtonElement", "webkitNotifications", "pageYOffset",
				"EntityReference", "NodeList", "screenY", "SVGAnimatedNumber",
				"webkitPerformance", "SVGTSpanElement", "navigator",
				"MimeTypeArray", "sessionStorage", "SVGPoint",
				"SVGScriptElement", "OverflowEvent", "HTMLTableColElement",
				"HTMLOptionElement", "HTMLInputElement",
				"SVGFEPointLightElement", "SVGPathSegList", "SVGImageElement",
				"defaultStatus", "SVGMarkerElement", "HTMLMetaElement",
				"HTMLLinkElement", "WebKitCSSTransformValue", "Clipboard",
				"HTMLTableElement", "SharedWorker", "SVGAElement",
				"SVGAnimatedRect", "SVGGElement", "toolbar",
				"SVGLinearGradientElement", "innerHeight",
				"SVGForeignObjectElement", "SVGAnimateElement",
				"applicationCache", "SVGFontElement", "pageXOffset",
				"SVGFontFaceElement", "Element",
				"SVGPathSegCurvetoQuadraticSmoothRel", "opener",
				"SVGStopElement", "CSSStyleSheet", "StyleSheetList",
				"TimeRanges", "HTMLHRElement", "WebKitPoint", "screenLeft",
				"SVGViewElement", "SVGGradientElement", "SVGPathSegMovetoRel",
				"HTMLDivElement", "CanvasPattern", "KeyboardEvent",
				"SVGHKernElement", "HTMLTitleElement", "HTMLQuoteElement",
				"SVGFEImageElement", "screenX", "SVGPathSegMovetoAbs",
				"RangeException", "SVGTextPathElement",
				"SVGAnimatedTransformList", "HTMLLegendElement",
				"SVGPathSegCurvetoQuadraticAbs", "MouseEvent", "MediaError",
				"HTMLObjectElement", "HTMLFontElement", "SVGFilterElement",
				"WebKitTransitionEvent", "MediaList", "SVGVKernElement",
				"SVGPaint",
				"SVGFETileElement",
				"Document",
				"XPathException",
				"innerWidth",
				"TextMetrics",
				"personalbar",
				"HTMLHeadElement",
				"SVGFEComponentTransferElement",
				"ProgressEvent",
				"SVGAnimatedPreserveAspectRatio",
				"Node",
				"SVGRectElement",
				"CSSPageRule",
				"SVGLineElement",
				"CharacterData",
				"length",
				"FileError",
				"SVGDocument",
				"MessagePort",
				"ClientRect",
				"Option",
				"SVGDescElement",
				"Notation",
				"StorageEvent",
				"HTMLFieldSetElement",
				"HTMLVideoElement",
				"locationbar",
				"SVGRenderingIntent",
				"SVGPathSegLinetoRel",
				"UIEvent",
				"HTMLTableRowElement",
				"HTMLDListElement",
				"File",
				"SVGEllipseElement",
				"SVGFEFuncRElement",
				"HTMLAllCollection",
				"CSSValue",
				"SVGAnimatedNumberList",
				"HTMLParamElement",
				"SVGElementInstance",
				"SVGPathSegLinetoHorizontalRel",
				"HTMLModElement",
				"outerHeight",
				"CSSFontFaceRule",
				"SVGPathSeg",
				"CSSStyleDeclaration",
				"WebSocket",
				"TouchEvent",
				"Rect",
				"StyleSheet",
				"SVGPathSegLinetoHorizontalAbs",
				"SVGColor",
				"SVGComponentTransferFunctionElement",
				"SVGStyleElement",
				"SVGNumberList",
				"Blob",
				"SVGFEFloodElement",
				"clientInformation",
				"HTMLStyleElement",
				"HTMLBaseElement",
				"HTMLBRElement",
				"FileReader",
				"SVGFEBlendElement",
				"HTMLHtmlElement",
				"SVGFEConvolveMatrixElement",
				"SVGFEGaussianBlurElement",
				"HTMLTextAreaElement",
				"HTMLBaseFontElement",
				"scrollbars",
				"screen",
				"localStorage",
				"defaultstatus",
				"SVGTextElement",
				"SVGFEOffsetElement",
				"RGBColor",
				"SVGGlyphElement",
				"HTMLCanvasElement",
				"ProcessingInstruction",
				"SVGZoomEvent",
				"HTMLFrameElement",
				"SVGElementInstanceList",
				"SVGFEDisplacementMapElement",
				"frames",
				"SVGPathSegCurvetoCubicSmoothRel",
				"HTMLElement",
				"HTMLSelectElement",
				"SVGFEDistantLightElement",
				"ImageData",
				"SVGFEFuncBElement",
				"HTMLIsIndexElement",
				"HTMLDocument",
				"SVGCircleElement",
				"HTMLCollection",
				"SVGSetElement",
				"SVGFEMergeElement",
				"HTMLDirectoryElement",
				"CSSMediaRule",
				"MessageEvent",
				"SVGFESpecularLightingElement",
				"DOMException",
				"SVGNumber",
				"SVGFontFaceSrcElement",
				"CSSRule",
				"SVGElement",
				"WebKitCSSMatrix",
				"status",
				"SVGMissingGlyphElement",
				"HTMLScriptElement",
				"DOMImplementation",
				"SVGLength",
				"HTMLOptGroupElement",
				"SVGPathSegLinetoVerticalAbs",
				"SVGTextPositioningElement",
				"styleMedia",
				"SVGFEFuncGElement",
				"HTMLAreaElement",
				"HTMLFrameSetElement",
				"SVGPathSegCurvetoQuadraticRel",
				"name", // "self"
				"HTMLIFrameElement", "Comment", "Event", "Storage",
				"XMLSerializer", "statusbar", "Range", "HTMLPreElement",
				"DOMStringList", "Image",
				"SVGPathSegCurvetoQuadraticSmoothAbs", "SVGRect", "parent",
				"SVGFontFaceFormatElement", "closed", "crypto",
				"CSSVariablesDeclaration", "SVGAnimateTransformElement",
				"HTMLOListElement", "HTMLFormElement",
				"SVGPathSegCurvetoCubicSmoothAbs", "DOMParser",
				"SVGPathSegClosePath", "console", "SVGPathSegArcRel",
				"EventException", "SVGAnimatedString", "SVGTransformList",
				"SVGFEMorphologyElement", "SVGAnimatedLength",
				"SVGPolygonElement", "scrollX", "SVGPathSegLinetoAbs",
				"HTMLMediaElement", "BlobBuilder", "XMLDocument",
				"SVGMaskElement", "HTMLHeadingElement", "XMLHttpRequest",
				"TextEvent", "event", "HTMLMeterElement", "SVGPathElement",
				"SVGStringList", "CSSVariablesRule", "HTMLAppletElement",
				"CanvasRenderingContext2D", "devicePixelRatio",
				"MessageChannel", "HTMLMarqueeElement",
				"WebKitCSSKeyframesRule", "XSLTProcessor", "CSSImportRule",
				"BeforeLoadEvent", "PageTransitionEvent", "CSSRuleList",
				"SVGAnimatedLengthList", "SVGTransform",
				"SVGTextContentElement", "HTMLTableSectionElement",
				"SVGRadialGradientElement", "HTMLTableCellElement",
				"SVGCursorElement", "DocumentFragment",
				"SVGPathSegCurvetoCubicAbs", "SVGUseElement", "FormData",
				"SVGPreserveAspectRatio", "HTMLMapElement", "XPathResult",
				"HTMLLIElement", "SVGSwitchElement", "SVGLengthList", "Plugin",
				"HTMLParagraphElement", "HTMLBlockquoteElement",
				"SVGPathSegArcAbs", "SVGAnimatedBoolean", "outerWidth",
				"CSSStyleRule", "SVGFontFaceUriElement", "Text",
				"HTMLUListElement", "SVGPointList", "CSSPrimitiveValue",
				"HTMLEmbedElement", "PluginArray", "SVGPathSegCurvetoCubicRel",
				"ClientRectList", "SVGMetadataElement", "SVGTitleElement",
				"SVGAnimatedAngle", "CSSCharsetRule", "menubar",
				"SVGAnimateColorElement", "SVGMatrix", "HTMLBodyElement",
				"SVGSymbolElement", "HTMLAudioElement", "CDATASection",
				"SVGFEDiffuseLightingElement", "SVGFETurbulenceElement",
				"SVGAnimatedEnumeration", "WebKitCSSKeyframeRule", "Audio",
				"SVGFEMergeNodeElement", "history", "Entity", "SQLException",
				"HTMLTableCaptionElement", "MimeType", "EventSource",
				"SVGException", "NamedNodeMap", "XMLHttpRequestUpload",
				"WebKitAnimationEvent", "SVGAnimatedInteger",
				"HTMLMenuElement", "SVGDefsElement", "SVGAngle",
				"SVGSVGElement", "XPathEvaluator", "HTMLImageElement",
				"NodeFilter", "SVGAltGlyphElement", "SVGClipPathElement",
				"Attr", "Counter", "SVGPolylineElement", "SVGPatternElement",
				"SVGFECompositeElement", "CSSValueList",
				"XMLHttpRequestException", "SVGFEColorMatrixElement",
				"SVGTRefElement", "WheelEvent", "SVGUnitTypes",
				"HTMLLabelElement", "HTMLAnchorElement", "SVGFEFuncAElement",
				"CanvasGradient", "frameElement", "DocumentType", "FileList",
				"scrollY", "HTMLProgressElement", "MutationEvent",
				"offscreenBuffering", "Worker", "SVGFontFaceNameElement",
				"screenTop", "onwebkittransitionend", "onmouseover",
				"onmouseup", "ondragend", "onerror", "onsearch", "close",
				"onabort", "onsuspend", "onkeydown", "postMessage", "onfocus",
				"ondurationchange", "onreset", "onkeyup", "onpause", "onended",
				"ondragenter", "onpagehide", "ondblclick", "onloadeddata",
				"ondragleave", "onvolumechange", "onbeforeunload", "onresize",
				"blur", "onloadstart", "onmousedown", "onloadedmetadata",
				"ondragstart", "onstalled", "onseeking", "ononline",
				"onkeypress", "onclick", "oninvalid", "onsubmit", "onpageshow",
				"onoffline", "onemptied", "onwebkitanimationiteration",
				"onprogress", "onstorage", "onload", "onwaiting", "oncanplay",
				"onratechange", "ondragover", "onunload", "onpopstate",
				"onplay", "onwebkitanimationstart", "onplaying",
				"oncanplaythrough", "onselect", "focus", "onmousemove",
				"ondrag", "onmessage", "onscroll", "ontimeupdate", "onchange",
				"oncontextmenu", "onmousewheel", "onblur", "onmouseout",
				"oninput", "ondrop", "onwebkitanimationend", "onseeked",
				"onhashchange", "getSelection", "print", "stop", "open",
				"showModalDialog", "alert", "confirm", "prompt", "find",
				"scrollBy", "scrollTo", "scroll", "moveBy", "moveTo",
				"resizeBy", "resizeTo", "getMatchedCSSRules", "setTimeout",
				"clearTimeout", "setInterval", "clearInterval", "atob", "btoa",
				"addEventListener", "removeEventListener", "captureEvents",
				"releaseEvents", "getComputedStyle",
				"webkitConvertPointFromPageToNode",
				"webkitConvertPointFromNodeToPage", "openDatabase",
				"dispatchEvent", "document", "parseInt",
				"Math", "eval", "decodeURIComponent", "encodeURIComponent", "arguments", "arguments.callee"};//added myself
		windowProps = Arrays.asList(windowPropsRaw);
	}

	public static final List<String> mouseEvent;
	static {
		String[] mouseEventPropsRaw = { "originalTarget", "type", "target",
				"currentTarget", "eventPhase", "bubbles", "cancelable",
				"timeStamp", "which", "rangeParent", "rangeOffset", "pageX",
				"pageY", "isChar", "getPreventDefault", "screenX", "screenY",
				"clientX", "clientY", "ctrlKey", "shiftKey", "altKey",
				"metaKey", "button", "relatedTarget", "initMouseEvent",
				"stopPropagation", "preventDefault", "initEvent", "view",
				"detail", "initUIEvent", "CAPTURING_PHASE", "AT_TARGET",
				"BUBBLING_PHASE", "mozPressure", "initNSMouseEvent",
				"explicitOriginalTarget", "preventBubble", "preventCapture",
				"isTrusted", "layerX", "layerY", "cancelBubble", "MOUSEDOWN",
				"MOUSEUP", "MOUSEOVER", "MOUSEOUT", "MOUSEMOVE", "MOUSEDRAG",
				"CLICK", "DBLCLICK", "KEYDOWN", "KEYUP", "KEYPRESS",
				"DRAGDROP", "FOCUS", "BLUR", "SELECT", "CHANGE", "RESET",
				"SUBMIT", "SCROLL", "LOAD", "UNLOAD", "XFER_DONE", "ABORT",
				"ERROR", "LOCATE", "MOVE", "RESIZE", "FORWARD", "HELP", "BACK",
				"TEXT", "ALT_MASK", "CONTROL_MASK", "SHIFT_MASK", "META_MASK",
				"SCROLL_PAGE_UP", "SCROLL_PAGE_DOWN" };
		mouseEvent = Arrays.asList(mouseEventPropsRaw);

	}

	public static final List<String> keyEvent;
	static {
		String[] keyEventPropsRaw = { "shiftKey", "returnValue",
				"currentTarget", "eventPhase", "timeStamp", "cancelable",
				"bubbles", "defaultPrevented", "altKey", "keyCode", "ctrlKey",
				"altGraphKey", "target", "layerY", "charCode", "pageX",
				"keyIdentifier", "detail", "type", "cancelBubble", "pageY",
				"clipboardData", "metaKey", "srcElement", "view",
				"keyLocation", "which", "layerX", "initKeyboardEvent",
				"initUIEvent", "stopPropagation", "preventDefault",
				"initEvent", "stopImmediatePropagation", "CAPTURING_PHASE",
				"AT_TARGET", "BUBBLING_PHASE", "MOUSEDOWN", "MOUSEUP",
				"MOUSEOVER", "MOUSEOUT", "MOUSEMOVE", "MOUSEDRAG", "CLICK",
				"DBLCLICK", "KEYDOWN", "KEYUP", "KEYPRESS", "DRAGDROP",
				"FOCUS", "BLUR", "SELECT", "CHANGE" };
		keyEvent = Arrays.asList(keyEventPropsRaw);
	}

	public static Set<String> keyMouseProps = new HashSet<String>(keyEvent);
	static {
		keyMouseProps.addAll(mouseEvent);
	}

	// element properties

	public static final Set<String> formElementProps;
	static {
		String[] formElementRaw = { "firstElementChild", "scrollHeight",
				"nodeType", "isContentEditable", "offsetParent", "hidden",
				"previousElementSibling", "parentElement", "children",
				"localName", "nodeValue", "ownerDocument", "lastElementChild",
				"offsetLeft", "tagName", "length", "className", "prefix",
				"innerHTML", "previousSibling", "namespaceURI", "enctype",
				"id", "childElementCount", "method", "lastChild", "scrollLeft",
				"innerText", "clientHeight", "target", "textContent",
				"nextSibling", "scrollWidth", "offsetHeight", "name",
				"clientWidth", "nodeName", "style", "lang", "scrollTop",
				"offsetTop", "childNodes", "baseURI", "nextElementSibling",
				"title", "firstChild", "attributes", "acceptCharset",
				"dataset", "outerText", "parentNode", "clientTop", "action",
				"tabIndex", "elements", "contentEditable", "outerHTML", "dir",
				"encoding", "noValidate", "offsetWidth", "clientLeft",
				"draggable", "submit", "reset", "checkValidity",
				"insertAdjacentHTML", "insertAdjacentText",
				"insertAdjacentElement", "getAttribute", "setAttribute",
				"removeAttribute", "getAttributeNode", "getElementsByTagName",
				"getAttributeNS", "setAttributeNS", "removeAttributeNS",
				"getElementsByTagNameNS", "getAttributeNodeNS", "hasAttribute",
				"hasAttributeNS", "focus", "blur", "scrollIntoView",
				"scrollIntoViewIfNeeded", "scrollByLines", "scrollByPages",
				"getElementsByClassName", "querySelector", "querySelectorAll",
				"webkitMatchesSelector", "getClientRects",
				"getBoundingClientRect", "setAttributeNode",
				"removeAttributeNode", "setAttributeNodeNS", "contains",
				"insertBefore", "replaceChild", "removeChild", "appendChild",
				"hasChildNodes", "cloneNode", "normalize", "isSupported",
				"hasAttributes", "lookupPrefix", "isDefaultNamespace",
				"lookupNamespaceURI", "addEventListener",
				"removeEventListener", "isSameNode", "isEqualNode",
				"compareDocumentPosition", "dispatchEvent", "ELEMENT_NODE",
				"ATTRIBUTE_NODE", "TEXT_NODE", "CDATA_SECTION_NODE",
				"ENTITY_REFERENCE_NODE", "ENTITY_NODE",
				"PROCESSING_INSTRUCTION_NODE", "COMMENT_NODE", "DOCUMENT_NODE",
				"DOCUMENT_TYPE_NODE", "DOCUMENT_FRAGMENT_NODE",
				"NOTATION_NODE", "DOCUMENT_POSITION_DISCONNECTED",
				"DOCUMENT_POSITION_PRECEDING", "DOCUMENT_POSITION_FOLLOWING",
				"DOCUMENT_POSITION_CONTAINS", "DOCUMENT_POSITION_CONTAINED_BY",
				"DOCUMENT_POSITION_IMPLEMENTATION_SPECIFIC" };
		formElementProps = new HashSet<String>(Arrays.asList(formElementRaw));
	}

	public static final Set<String> anchorElementProps;
	static {
		String[] anchorElementRaw = { "scrollHeight", "accessKey",
				"clientLeft", "nodeType", "firstElementChild", "offsetParent",
				"offsetWidth", "protocol", "isContentEditable", "hidden",
				"children", "previousElementSibling", "href", "localName",
				"ownerDocument", "nodeValue", "lastElementChild", "offsetLeft",
				"tagName", "className", "prefix", "innerHTML",
				"previousSibling", "host", "namespaceURI", "scrollLeft", "id",
				"lastChild", "innerText", "clientHeight", "target",
				"textContent", "nextSibling", "scrollWidth", "shape",
				"hreflang", "offsetHeight", "name", "charset", "clientWidth",
				"nodeName", "style", "lang", "scrollTop", "offsetTop",
				"pathname", "childNodes", "baseURI", "nextElementSibling",
				"type", "hostname", "title", "firstChild", "attributes",
				"dataset", "coords", "search", "port", "parentNode",
				"clientTop", "tabIndex", "contentEditable", "hash", "dir",
				"outerHTML", "text", "outerText", "childElementCount",
				"parentElement", "rel", "draggable", "rev",
				"insertAdjacentHTML", "insertAdjacentText",
				"insertAdjacentElement", "getAttribute", "setAttribute",
				"removeAttribute", "getAttributeNode", "getElementsByTagName",
				"getAttributeNS", "setAttributeNS", "removeAttributeNS",
				"getElementsByTagNameNS", "getAttributeNodeNS", "hasAttribute",
				"hasAttributeNS", "focus", "blur", "scrollIntoView",
				"scrollIntoViewIfNeeded", "scrollByLines", "scrollByPages",
				"getElementsByClassName", "querySelector", "querySelectorAll",
				"webkitMatchesSelector", "getClientRects",
				"getBoundingClientRect", "setAttributeNode",
				"removeAttributeNode", "setAttributeNodeNS", "contains",
				"insertBefore", "replaceChild", "removeChild", "appendChild",
				"hasChildNodes", "cloneNode", "normalize", "isSupported",
				"hasAttributes", "lookupPrefix", "isDefaultNamespace",
				"lookupNamespaceURI", "addEventListener",
				"removeEventListener", "isSameNode", "isEqualNode",
				"compareDocumentPosition", "dispatchEvent", "ELEMENT_NODE",
				"ATTRIBUTE_NODE", "TEXT_NODE", "CDATA_SECTION_NODE",
				"ENTITY_REFERENCE_NODE", "ENTITY_NODE",
				"PROCESSING_INSTRUCTION_NODE", "COMMENT_NODE", "DOCUMENT_NODE",
				"DOCUMENT_TYPE_NODE", "DOCUMENT_FRAGMENT_NODE",
				"NOTATION_NODE", "DOCUMENT_POSITION_DISCONNECTED",
				"DOCUMENT_POSITION_PRECEDING", "DOCUMENT_POSITION_FOLLOWING",
				"DOCUMENT_POSITION_CONTAINS", "DOCUMENT_POSITION_CONTAINED_BY",
				"DOCUMENT_POSITION_IMPLEMENTATION_SPECIFIC" };
		anchorElementProps = new HashSet<String>(Arrays.asList(anchorElementRaw));
	}
	
	public static Set<String> elementProps = new HashSet<String>();
	static{
		elementProps.addAll(anchorElementProps);
		elementProps.addAll(formElementProps);
	}
	
	
	public static void main(String[] args) {
		anchorElementProps.removeAll(formElementProps);
		System.out.println(anchorElementProps);
	}
}
